version: '3'

services:
  db:
    image: postgres:13
    container_name: tarzan-memory
    env_file:
      - .env
    ports:
      - "5432:5432"

  tarzan-box:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarzan-box
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
