version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    container_name: tarzan-box
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    environment:
      - HOST_PORT=${HOST_PORT}
    command: ["./django-utils.sh", "${HOST_PORT}"]
