version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: tarzan-db
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  web:
    build:
      context: .
    container_name: tarzan-web
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    environment:
      - HOST_PORT=${HOST_PORT}
    command: ["./scripts/django-deploy.sh", "${HOST_PORT}"]
    volumes:
      - .:/app
  redis:
    image: redis:latest
    container_name: tarzan-redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  celery:
    build:
      context: .
    container_name: tarzan-celery
    depends_on:
      - redis
      - web
    env_file:
      - .env
    command: celery -A src worker -l info
  flower:
    build:
      context: .
    container_name: tarzan-flower
    depends_on:
      - celery
    env_file:
      - .env
    command: celery -A src --broker=${CELERY_BROKER_URL} flower
