version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: tarzan-db
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  web:
    build:
      context: .
    container_name: tarzan-web
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${HOST_PORT}"
    depends_on:
      - db
    environment:
      - HOST_PORT=${HOST_PORT}
    command: ["./django-deploy.sh", "${HOST_PORT}"]
  celery:
    build:
      context: .
    container_name: tarzan-celery
    env_file:
      - .env
    depends_on:
      - db
    command: celery -A src worker -l info
  flower:
    build:
      context: .
    container_name: tarzan-flower
    env_file:
      - .env
    depends_on:
      - db
    command: flower -A src --port=${FLOWER_PORT}