version: '3'

services:
  # Your Django application
  web:
    image: tarzan-image:latest
    container_name: tarzan-box
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    working_dir: /app
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: tarzan-memory
    env_file:
      - .env
    ports:
      - "5432:5432"
