[tool.poetry]
name = "tarzan"
version = "0.0.0"
description = "My first Django package"
authors = ["Bruno Peixoto <brunolnetto@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
psycopg2-binary = "^2.9.7"
django-rest-swagger = "^2.2.0"
djangorestframework = "^3.14.0"
python-decouple = "^3.8"

[tool.poetry.group.dev.dependencies]
Django = "^4.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
