name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Poetry and pylint
      run: |
        # Install Poetry if not already installed
        curl -sSL https://install.python-poetry.org | python -
        # Configure Poetry to use the correct Python version
        python -m poetry env use ${{ matrix.python-version }}
      
    - name: Set up Poetry and pylint
      run: |
        pip install pylint-django
        
    - name: Install project dependencies
      run: |
        # Install dependencies using Poetry
        poetry install

    - name: Analyze the code with pylint
      run: |
        # Run Pylint on Python files
        pylint $(git ls-files '*.py')