name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt  # Replace with the path to your requirements file

    - name: Set PYTHONPATH
      run: |
        export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"

    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '*.py')
